### ISSUE TITLE
Add  New Python Script

### ISSUE THREAD

**Issue by Logan1x** [Logan1x/Python-Scripts#1]
Its an open source python project ( **Python Script Collection** ) Repository so if you have any new python script please consider adding in it to make this project more beautiful.
Thanks.

**NOTE:**
* Add **new branch** for every Pull Request.

**Comment by Pradhvan** [comment]
Let me pick this one , I will add some web scrapping scripts.

**Comment by Logan1x** [comment]
Sure @Pradhvan

**Comment by Logan1x** [comment]
Add them to the root folder [here](Logan1x/Python-Scripts) do not make folder's i am removing them

**Comment by Logan1x** [comment]
and can you provide me your profile picture link i am in love with it😜

**Comment by Pradhvan** [comment]
It's by [Justin Maller](http://justinmaller.com/) the same guy you have your profile picture .

**Comment by Pradhvan** [comment]
I will wait first to merge that PR than will do a PR so the file structure of the is changed.

**Comment by toonarmycaptain** [comment]
I've got a script that takes location input, filesize input, then returns all of the files larger than that size?

**Comment by Logan1x** [comment]
Thank you So much for this 😍

> It's by Justin Maller the same guy you have your profile picture .

**Comment by Logan1x** [comment]
@toonarmycaptain  now you can send PR.

**Comment by kalbhor** [comment]
I have a script that adds metadata (Artist name, album name, album art) to all music files. Should I add it here?

**Comment by Logan1x** [comment]
@kalbhor  yes you can add these here if they are python scripts and update readme as well😊

**Comment by toonarmycaptain** [comment]
Added findlargefiles, updated README.

**Comment by RodolfoFerro** [comment]
This is an awesome project @Logan1x !
I'll add some scripts that I've been creating for 'Intro to Python' workshops. 😃 👍 
(How to plot using matplotlib, face detection with OpenCV, etc.)

**Comment by vigov5** [comment]
@Logan1x I added a simple script to automate add users (>200+) to twitter list. Hope this help 😄

**Comment by akshitgrover** [comment]
I have a python script with GUI embedded which uses file handling to calculate and store expenses in a month and year. Should I create a PR?

**Comment by Logan1x** [comment]
yes you should @akshitgrover .

**Comment by akshitgrover** [comment]
Doing it right away.

**Comment by akshitgrover** [comment]
@Logan1x I created PR.

**Comment by akshitgrover** [comment]
@Logan1x should I update readme?

**Comment by Logan1x** [comment]
@akshitgrover  yes you have to ..

**Comment by akshitgrover** [comment]
@Logan1x Another PR then?

**Comment by Logan1x** [comment]
no, if you have done in last one ...

**Comment by akshitgrover** [comment]
@Logan1x, for now, it is partially merged, right?
I mean when will it get merged fully?

**Comment by Logan1x** [comment]
> I mean when will it get merged fully?

partially merged what's that?

**Comment by akshitgrover** [comment]
@Logan1x it is still in review, it not merged fully.

**Comment by Logan1x** [comment]
Can you reference the pr?

**Comment by amanagarwal-sopho** [comment]
Can i add a subtitle downloader?

**Comment by Logan1x** [comment]
@amanagarwal-sopho  yes! you can...

**Comment by akshitgrover** [comment]
@Logan1x I have a script which is used for image encoding and decoding, Should I create a PR?

**Comment by Logan1x** [comment]
@akshitgrover yes! Create PR and don't forget to star the project 😊

**Comment by MadhavBahlMD** [comment]
Can i add a script that fetches data from serial board and updates it to firebase?

**Comment by akshitgrover** [comment]
@Logan1x I have a program to implement basic end to end encryption, I am creating a PR maybe you can look to it.

**Comment by akshitgrover** [comment]
@Logan1x I am working on basics on Server and client communication, for which I have developed a basic python script, Maybe I can create a PR, Look forward to it.

**Comment by Logan1x** [comment]
Requested some changes please have look at it @akshitgrover

**Comment by akshitgrover** [comment]
@Logan1x Resolved. #27

**Comment by MadhavBahlMD** [comment]
Can i add a script which reads data from firebase database and if the fetched data is above some certain limit, it sends an email to the registered user?

**Comment by Logan1x** [comment]
@MadhavBahlMD  if it's made by you or open sourced😊

**Comment by Maybeking** [comment]
#31

**Comment by Logan1x** [comment]
@Maybeking  asked some changes, check your pr.

**Comment by akshitgrover** [comment]
@Logan1x I have a python script to get lyrics for all the songs in the current directory and save them in a single lyrics.txt file, I am creating a PR maybe you can look to it.

**Comment by dgupta777** [comment]
I want to add python script for Lost Robot quiz of ACM-ICPC  India Regionals -2016-17.

**Comment by niharikakrishnan** [comment]
I have written a python script that is does sentiment analysis of twitter feeds on the topic of demonetization and produces the analysis in terms of graphs using matplotlib.

**Comment by AbhishekVarghese** [comment]
Can someone write a python script to convert data in these types of files into images ?
I think the reverse i.e. image to vector data is already present.

http://yann.lecun.com/exdb/mnist/

**Comment by mr-shades** [comment]
Hey can I add a face and eye detection python script that uses opencv

**Comment by Rafi993** [comment]
Hi all thanks for your awesome scripts. It is better to close this issue and open issue pertaining to each scripts separately if needed since this issue is more generalized and might make it hard to search and the discussions could be moved to gitter channel.

**Comment by Rafi993** [comment]
Here is the gitter link https://gitter.im/Python_Scripts/Lobby# for those who are looking for it lets continue our discussion there :)
