### ISSUE TITLE
Redesign The Repo

### ISSUE THREAD

**Issue by Logan1x** [Logan1x/Python-Scripts#2]
Script in the folder is not looking good to me, If you can put them outside of folder [here](https://github.com/Logan1x/Python-Scripts), this would look more fine.

Add Your name in readme.md after contributing😊.

**Comment by KayvanMazaheri** [comment]
I'm willing to work on this.  
can you assign it to me?

**Comment by Logan1x** [comment]
![selection_003](https://user-images.githubusercontent.com/10944610/31007083-e8730080-a51c-11e7-84aa-fdb43bc5c22b.png)
 i am having bit problem do you have any idea about this?

**Comment by KayvanMazaheri** [comment]
Not Really ! :smile:

**Comment by Logan1x** [comment]
It's Okay. I amlooking into it.

**Comment by TheCodeArtist** [comment]
> if you can put them outside of folder here, this would look more fine.
While moving the py scripts to the root of the repo,
what about the rest of the files (README and LICENSE) in the directories?

**Comment by Logan1x** [comment]
LICENSE will be commom for all and one readme.md file will consist of all the project description @TheCodeArtist

**Comment by pradyunsg** [comment]
@Logan1x You cannot assign an issue to someone who does not have commit access to the repository. :)

**Comment by pradyunsg** [comment]
I would be interested in taking this on too.

**Comment by Logan1x** [comment]
Can you provide source for this 

> You cannot assign an issue to someone who does not have commit access to the repository. :)

**Comment by Logan1x** [comment]
Sorry for this 

> I would be interested in taking this on too.

this issue is alredy working by @KayvanMazaheri  
you both can consult and divide work if you want to ...

**Comment by pradyunsg** [comment]
> By commit access you mean collaborator ?

Yep. :)

**Comment by pradyunsg** [comment]
> this issue is alredy working by

Cool. No issues. :)

**Comment by Logan1x** [comment]
@pradyunsg  source please

> Yep. :)

**Comment by pradyunsg** [comment]
Uhm... experience?

Anyway, a google search for "GitHub assign issues" leads to https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/ where you can see that in the tips section it says:

> If you have write access to a repository, you can assign issues and pull requests to yourself, collaborators on personal projects, or members of your organization with read permissions on the repository.

**Comment by prakashdanish** [comment]
This still doesn't looks assigned to someone to me, can someone assign me?

**Comment by Logan1x** [comment]
@pradyunsg  are you refering to this line...

> 

    If you have write access to a repository, you can assign issues and pull requests to yourself, collaborators on personal projects, or members of your organization with read permissions on the repository.


if you are then it says if you have write access then you can add yourself. collaborators, and **other members with read permission**...

**Comment by Logan1x** [comment]
@prakashdanish  It's already assigned to someone else due to some error i am not able to add him as assignee😞. 
You have a good profile page why are you looking for small contribution you should focus on org.

**Comment by pradyunsg** [comment]
@Logan1x

> members of your organization

This is a personal project, not an organisation's project; which is why you can't do that.

> collaborators on personal projects

If you want to add @KayvanMazaheri (or whoever) as the assignee, they need to be a collaborator (i.e. able to push commits to this repository). If you're not comfortable with that, feel free to just mention that that person is going to tackle that issue in the OP -- the description of the issue.

---

> if you are then it says if you have write access then you can add yourself. collaborators, and other members with read permission...so no need to be collaborator.

I think I should mention that this comes across as snarky; it is not really nice to be on the receiving end of such a comment -- emphasis added, quoted content modified to suit your position, almost sarcastic -- it feels like you're saying I can't read. I was trying to help you here but now I don't think it's a good use of my free time to do so.

I assume, in good faith, this was not your intention but please be careful about what the tone of your comments are in the future.

**Comment by pradyunsg** [comment]
As an aside, putting all the scripts in a `bin` directory is also an idea that someone might want to explore.

**Comment by pradyunsg** [comment]
> you should focus on org

Oh well... Please don't tell people what to do. There's a better way to say let someone with less experience do this.

That's about all I'm going to say here.

**Comment by Logan1x** [comment]
@pradyunsg  I sorry for the way you felt my intension's was not to hurt you in any sense. I want to conform and solve this problem asap and i didn't know the source you mentioned had wrriten for org. It's my first time as maintainer so this problem occured . Sorry for the experience you had

**Comment by pradyunsg** [comment]
> Sorry for the experience you had

No issues. :)

> It's my first time as maintainer

Text is a bad medium for conveying emotion. 🤷‍♂️ 

> If you want to add @KayvanMazaheri (or whoever) as the assignee, they need to be a collaborator (i.e. able to push commits to this repository). If you're not comfortable with that, feel free to just mention that that person is going to tackle that issue in the OP -- the description of the issue.

You might want to give this a shot.

**Comment by Logan1x** [comment]
Next time surely because i already received PR and closing this issue now.

**Comment by prakashdanish** [comment]
@Logan1x sorry, didn't read the description of the issue.

**Comment by Logan1x** [comment]
No Problem 😊 @prakashdanish
