### ISSUE TITLE
Align the Star image to line 

### ISSUE THREAD

**Issue by Logan1x** [Logan1x/Python-Scripts#26]
![selection_015](https://user-images.githubusercontent.com/10944610/31428989-5a216944-ae8a-11e7-9af7-226814e9ed09.png)
The image in this [line](https://github.com/Logan1x/Python-Scripts#if-you-like-the-project-give-a-star----) is not aligned to the line. 
Move it down so it look aligned.

**Comment by sagar-kalra** [comment]
I would like  to work on this issue . @Logan1x

**Comment by Logan1x** [comment]
Sure go on @sagar-kalra

**Comment by sagar-kalra** [comment]
@Logan1x can you help me out?
i tried various options but they arent working.

**Comment by Logan1x** [comment]
@ValentinChCloud  helping you right? @sagar-kalra
