### ISSUE TITLE
How can we make this project more better?

### ISSUE THREAD

**Issue by Logan1x** [Logan1x/Python-Scripts#82]
Suggest idea's to make this project better than ever....
you can include 

- [ Suggestion ] 

- [ FeedBack ]

**Comment by Rafi993** [comment]
How about writing unit tests for each scripts

**Comment by Logan1x** [comment]
> WishList.md where people could write about scripts

looks like a good idea, We have to copy the list of the script and paste there.

>making unit tests mandatory

I am not a pro coder ... I've never written unit tests before( will need more help on this).

>  We could remove the list of scripts from README.md and put in a separate git page making it searchable and freeing it of clutter.

yes this can be done.

**Comment by Rafi993** [comment]
I'll close this issue since it is more general and we could continue our discussion in the gitter channel. Here is the link for those who are looking for it https://gitter.im/Python_Scripts/Lobby# :)
